import {
  IconBarbell,
  IconBeach,
  IconBooks,
  IconCar,
  IconCarCrash,
  IconChartLine,
  IconCreditCardPay,
  IconDeviceGamepad,
  IconDevicesPc,
  IconFireExtinguisher,
  IconGift,
  IconHealthRecognition,
  IconHomeDollar,
  IconPaw,
  IconPerfume,
  IconPigMoney,
  IconRollerSkating,
  IconShoppingCart,
  IconTax,
  IconToolsKitchen2,
} from "@tabler/icons-react";

export const CATEGORY_ICONS: {
  [key: string]: React.ComponentType<{ color: string; size: number }>;
} = {
  housing: IconHomeDollar,
  food: IconToolsKitchen2,
  transport: IconCar,
  healthcare: IconHealthRecognition,
  insurance: IconCarCrash,
  debtPayments: IconCreditCardPay,
  savings: IconPigMoney,
  investments: IconChartLine,
  education: IconBooks,
  shopping: IconShoppingCart,
  entertainment: IconDeviceGamepad,
  travel: IconBeach,
  sport: IconBarbell,
  personalCare: IconPerfume,
  gifts: IconGift,
  pets: IconPaw,
  taxes: IconTax,
  technology: IconDevicesPc,
  hobbies: IconRollerSkating,
  emergency: IconFireExtinguisher,
};
