import type { Category } from "@/types/category.type";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: `c1`,
    name: "Food & Dinning",
    budget: 600,
    type: "expense",
    iconName: "food",
    color: "orange",
  },
  {
    id: `c2`,
    name: "Shopping",
    budget: 400,
    type: "expense",
    iconName: "shopping",
    color: "pink",
  },
  {
    id: `c3`,
    name: "Rent",
    budget: 1200,
    type: "expense",
    iconName: "housing",
    color: "red",
  },
  {
    id: `c4`,
    name: "Entertainment",
    budget: 200,
    type: "expense",
    iconName: "entertainment",
    color: "sky",
  },
  {
    id: `c5`,
    name: "Education",
    budget: 300,
    type: "expense",
    iconName: "education",
    color: "blue",
  },
  {
    id: `c6`,
    name: "HealthCare",
    budget: 150,
    type: "expense",
    iconName: "healthcare",
    color: "pinkred",
  },
  {
    id: `c7`,
    name: "Transportation",
    budget: 300,
    type: "expense",
    iconName: "transport",
    color: "purple",
  },
  {
    id: `c8`,
    name: "Salary",
    budget: 0,
    type: "income",
    iconName: "savings",
    color: "green",
  },
  {
    id: `c9`,
    name: "Investment",
    budget: 0,
    type: "income",
    iconName: "investments",
    color: "aquagreen",
  },
] as const;
